version: '3.8'

services:
  web:
    build: .
    command:  command: bash -c "python manage.py collectstatic --noinput && gunicorn guan_shu.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=guan_shu.settings
